spring:
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        namespace: cssz
        group: LOCAL_DEV
        # username: nacos
        # password: nacos
      discovery:
        server-addr: ${spring.cloud.nacos.config.server-addr}
        namespace: ${spring.cloud.nacos.config.namespace}
        group: auto_host_${COMPUTERNAME:${HOSTNAME:unknown}}
        # username: ${spring.cloud.nacos.config.username}
        # password: ${spring.cloud.nacos.config.password}
  config:
    import:
      - classpath:config/infra.yml
      - classpath:config/jeecg.yml
      - optional:nacos:infra.yml
      - optional:nacos:jeecg.yml
